export const projectList = [
  {
    id: 1,
    title: 'Unico Cafe Attendance App',
    desc: 'The Cafe Unico attendance web app allows employees to check in and out using a webcam while detecting their location. With real-time tracking and geolocation features, the app ensures that employees are present at the cafe during attendance. The dashboard provides managers with attendance stats, including daily check-ins, working hours, and location verification. This system simplifies attendance management and enhances security by ensuring accurate time and location tracking.',
    tools: ['Laravel', 'MySQL', 'Geolocation', 'WebcamJS'],
    image: '/images/attendance.png',
    category: 'website',
    url: 'https://github.com/talithaalda/PresensiUnico.git',
    domain: '',
  },
  {
    id: 2,
    title: 'Chat App',
    desc: 'This chat application enables real-time communication between users using a Ruby on Rails backend and a React frontend. It features real-time messaging through WebSocket, allowing users to send and receive messages instantly. ',
    tools: ['Ruby on Rails', 'ReactJS', 'JavaScript', 'SQLite3'],
    image: '/images/ChatApp.png',
    category: 'website',
    url: 'https://github.com/talithaalda/chat-room',
    domain: 'https://letstalk.my.id/',
  },
  {
    id: 3,
    title: 'WLC Media',
    desc: 'Digital platform that connects brands with talent for social media product endorsements. The website includes an admin CMS feature that allows businesses to efficiently manage talent data and streamline their campaigns.',
    tools: ['Next JS', 'Bootstrap', 'JavaScript', 'CSS'],
    image: '/images/wlcmedia.png',
    category: 'website',
    url: 'https://github.com/talithaalda/WLC-Media',
    domain: 'https://wlc-media.vercel.app/',
  },
  {
    id: 4,
    title: 'Waste Classification',
    desc: 'A website designed to identify various types of waste, including plastic, paper, organic matter, metal, glass, and cardboard. Powered by TensorFlow, the platform offers an efficient way to classify waste types accurately.',
    tools: ['TensorFlow', 'FlaskAPI', 'Python', 'JavaScript'],
    image: '/images/wasteclassification.png',
    category: 'ml',
    url: 'https://github.com/talithaalda/waste-classification-web-service',
    domain: '',
  },
  {
    id: 5,
    title: 'Portal PLN Nusantara Power',
    desc: 'A website that delivers news updates, event agendas, calendars, and quick access to applications, specifically designed for PT PLN Nusantara Power employees.',
    tools: ['Laravel', 'Bootstrap', 'JavaScript'],
    image: '/images/portalpln.png',
    category: 'website',
    url: 'https://github.com/talithaalda/portalpln',
    domain: 'https://portal.talproject.my.id/',
  },
  {
    id: 6,
    title: 'Teman Bearly - Ecommerce Website',
    desc: 'Platform that offers a wide selection of skincare and makeup products for purchase, along with payment options. Developed using the Laravel framework and supported by a database, this website provides a seamless and convenient online shopping experience.',
    tools: ['Laravel', 'Bootstrap', 'JavaScript'],
    image: '/images/temanbearly.png',
    category: 'website',
    url: 'https://github.com/talithaalda/temanbearly1',
    domain: 'https://temanbearly.talproject.my.id/',
  },
  {
    id: 7,
    title: 'Dapur Panen',
    desc: 'Catering website that offers a wide selection of delicious, freshly prepared meals for various events and occasions. From personalized menus to professional delivery services, DapurPanen ensures a convenient and delightful dining experience for every customer.',
    tools: ['Laravel', 'Bootstrap', 'JavaScript'],
    image: '/images/dapurpanen.png',
    category: 'website',
    url: 'https://github.com/talithaalda/DapurPanen',
    domain: 'https://dapurpanen.talproject.my.id/',
  },
  {
    id: 8,
    title: 'Re-desain Web Tiket Wisata Surabaya',
    desc: "The Surabaya Tourist Tickets website redesign project, crafted using Figma, aims to create a modern and user-friendly interface. The redesigned platform will enhance the booking experience for visitors, making it easier to explore and purchase tickets for Surabaya's top attractions.catering website that offers a wide selection of delicious, freshly prepared meals for various events and occasions. From personalized menus to professional delivery services.",
    tools: ['Figma'],
    image: '/images/tiketwisatasurabaya.png',
    category: 'uiux',
    url: 'https://www.figma.com/design/w3sbI0psbRLTzcrTFWsvpr/Tiket-wisata?node-id=0-1&t=lteuWBrDhHtHsynt-1',
    domain: '',
  },
]
